In [ ]:
!nvidia-smi

Thu Jun 27 14:43:58 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   47C    P0              27W /  70W |    121MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


#Introduction to tensors


###Creating Tensors

In [ ]:
#scalar
#pytorch tensors are created using torch.tensor()
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
#To get dimensionality
scalar.ndim

0

In [ ]:
#To get tensor back as an int
scalar.item()

7

In [ ]:
#Vector (Magnitude and direction)
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
#vector[0]
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#Matrix
matrix = torch.tensor([[7, 8],[9, 10]])
matrix
#In pytorch when we encode data into numbers, it will be of the tensor data type

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
#To access matrix elements
matrix[0]

tensor([7, 8])

In [ ]:
#Tensor
tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [5, 10, 15]]])
tensor

tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [ 5, 10, 15]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
tensor[0][1][1]

tensor(6)

## Random Tensors

Random tensors are important as neural networks start with tensors full of random numbers and then adjust those numbers to better represent the data.

Loop:
1- Start with random numbers
2- Look at data
3- Update random numbers

In [ ]:
#Creating a random tensor of size (3,4)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1599, 0.8993, 0.2426, 0.5457],
        [0.4477, 0.7485, 0.4445, 0.1706],
        [0.7116, 0.7681, 0.6658, 0.0713]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#Creating random tensor with a similar shape to an image tensor
image_size_tensor = torch.rand(size = (224, 224, 3)) #Height, Width, Colour channels (R, G, B) #writing size is optional, no issue
image_size_tensor.ndim, image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

###0 & 1 Tensors

In [ ]:
#Creating a tensor of all 0
zero_tensor = torch.zeros(3, 4)
zero_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#Creating a tensor of all 1
one_tensor = torch.ones(3,4)
one_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
one_tensor.dtype
#default data type is always float 32, we need to explicitly change it if needed.

torch.float32

###Creating a tensor with a range

In [ ]:
one_to_ten = torch.arange(1, 11) #starting inclusive, ending exclusive
print(one_to_ten)
torch.arange(start = 5, end = 100, step = 5)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


tensor([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
        95])

In [ ]:
#creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

Note : Tensor datatypes is one of the three main common issues you run into in pytorch

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device e.g 1 tensor on gpu and 1 tensor on cpu, will lead to error



In [ ]:
#Float 32 tensor
float_32_tensor = torch.tensor([1.0, 2.0, 3.0],
                               dtype = None, #what datatype is the tensor e.g float32, float16
                               device = "cuda", #where tensor is going to be located
                               requires_grad = False) #Wheter or not to track gradients with this tensors operations.
float_32_tensor, float_32_tensor.dtype

(tensor([1., 2., 3.], device='cuda:0'), torch.float32)

In [ ]:
#Changing datatype of a tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([1., 2., 3.], device='cuda:0', dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([1., 4., 9.], device='cuda:0')

In [ ]:
int_32_tensor = torch.tensor([3,6,9],
                             dtype = torch.int32,
                             device = "cuda")
int_32_tensor

tensor([3, 6, 9], device='cuda:0', dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 3., 12., 27.], device='cuda:0')

### Getting information from tensors (Tensor attributes)
1. To get the datatype, use tensor.dtype
2. To get the shape, use tensor.shape
3.To get the device, use tensor.device


In [ ]:
info_tensor = torch.rand(3, 4,
                         dtype = torch.float32,
                         device = "cuda")
info_tensor

tensor([[0.7588, 0.4904, 0.2327, 0.6310],
        [0.5165, 0.2850, 0.7170, 0.1042],
        [0.9143, 0.7350, 0.8542, 0.3963]], device='cuda:0')

In [ ]:
print(info_tensor)
print(f"Datatype of tensor : {info_tensor.dtype}")
print(f"Shape of tensor: {info_tensor.shape}")
print(f"Device of tensor: {info_tensor.device}")

tensor([[0.7588, 0.4904, 0.2327, 0.6310],
        [0.5165, 0.2850, 0.7170, 0.1042],
        [0.9143, 0.7350, 0.8542, 0.3963]], device='cuda:0')
Datatype of tensor : torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cuda:0


###Manipulating Tensors (Tensor Operations)
1. Addition
2. Subtraction
3. Multiplication(Element-wise)
4. Matrix Multiplication

In [ ]:
operation_tensor = torch.tensor([1, 2, 3])
operation_tensor.dtype, operation_tensor + 10 #new values not assigned to tensor.

(torch.int64, tensor([11, 12, 13]))

In [ ]:
operation_tensor * 10

tensor([10, 20, 30])

In [ ]:
operation_tensor - 1

tensor([0, 1, 2])

In [ ]:
operation_tensor = torch.mul(operation_tensor,2) #Element-wise Multiplication
operation_tensor

tensor([2, 4, 6])

In [ ]:
operation_tensor = torch.div(operation_tensor, 2)
operation_tensor

tensor([1., 2., 3.])

In [ ]:
#Element-wise multiplication
print(operation_tensor)
operation_tensor * operation_tensor #Multiplying the tensor by itself

tensor([1., 2., 3.])


tensor([1., 4., 9.])

In [ ]:
#Matrix Multiplication (Dot-Product)
print(f"The original tensor is {operation_tensor}")
torch.matmul(operation_tensor, operation_tensor)
# 1x1 + 2x2 + 3x3 = 14 (Every row is multiplied by every column)

The original tensor is tensor([1., 2., 3.])


tensor(14.)

In [ ]:
#Manual matrix multiplication
%%time
value = 0
for i in range(len(operation_tensor)):
  value = value + (operation_tensor[i] * operation_tensor[i])
print(value)

tensor(14.)
CPU times: user 857 µs, sys: 955 µs, total: 1.81 ms
Wall time: 2.51 ms


In [ ]:
%%time
torch.matmul(operation_tensor, operation_tensor)
#Much faster

CPU times: user 38 µs, sys: 0 ns, total: 38 µs
Wall time: 40.8 µs


tensor(14.)

###Rules for matrix multiplication:
Rule 1. **Inner Dimensions** must match
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
* (@ is a symbol for matrix multiplication)

In [ ]:
torch.matmul(torch.rand(3,2), torch.rand(3,2)) #will not work. 3 rows 2 columns for both matrices, imagine it Inner dimension mismatch

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
torch.matmul(torch.rand(2,3), torch.rand(3,2)) #Inner dimensions match ... 3, 3

tensor([[0.6390, 0.6704],
        [0.8761, 0.9698]])

Rule 2. Resulting matrix has the shape of the **Outer Dimension**
* `(2, 3) @ (3, 2)` --> `(2, 2)` (Outer dimension is 2)
* `(3, 2) @ (2, 3)` --> `(3, 3)` (Outer dimension is 3)

In [ ]:
rule_tensor = torch.matmul(torch.rand(3,2), torch.rand(2,3)) #Inner dimesions match ... 2, 2
print(rule_tensor)
print(rule_tensor.shape) # The resulting shape is (3, 3) as the outer dimension was 3

tensor([[0.2607, 1.0321, 0.3917],
        [0.1623, 0.4425, 0.1624],
        [0.1453, 0.6054, 0.2306]])
torch.Size([3, 3])


###**Shape Errors**

In [ ]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

print(f"The shapes of the tensors are {tensor_A.shape}, {tensor_B.shape}")
print("The inner dimesions don't match so there will be an error.")
torch.matmul(tensor_A, tensor_B)

The shapes of the tensors are torch.Size([3, 2]), torch.Size([3, 2])
The inner dimesions don't match so there will be an error.


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

* To fix our shape issues, we can manipulate the shape of one of our tensors using transpose.
*A transpose switches the axis or dimensions of a given tensor.

In [ ]:
print("Tensor B before transpose is :")
print(tensor_B)
print("\nShape of tensor B before transpose is :")
print(tensor_B.shape)
print("\nTensor B after tranpose is :")
tensor_B = tensor_B.T
print(tensor_B)
print("\nShape of tensor B after transpose is :")
print(tensor_B.shape)

Tensor B before transpose is :
tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

Shape of tensor B before transpose is :
torch.Size([3, 2])

Tensor B after tranpose is :
tensor([[ 7,  8,  9],
        [10, 11, 12]])

Shape of tensor B after transpose is :
torch.Size([2, 3])


In [ ]:
print(f"Tensor A is:\n {tensor_A}")
print(f"\nTensor B is: \n {tensor_B}")

tensor_C = torch.matmul(tensor_A, tensor_B) #Will get a different answer if we flip tensor_A and tensor_B
print(f"\nThe answer of multiplying tensor_A and tensor_B is:\n {tensor_C}")
print(f"The shape of the resulting tensor C is {tensor_C.shape}")

Tensor A is:
 tensor([[1, 2],
        [3, 4],
        [5, 6]])

Tensor B is: 
 tensor([[ 7,  8,  9],
        [10, 11, 12]])

The answer of multiplying tensor_A and tensor_B is:
 tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
The shape of the resulting tensor C is torch.Size([3, 3])


###Finding the min, max, mean, sum of tensors (Tensor aggregation)

In [ ]:
aggregation_tensor = torch.arange(0, 100, 10)
aggregation_tensor, aggregation_tensor.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
#Finding the min
aggregation_tensor.min(), torch.min(aggregation_tensor)

(tensor(0), tensor(0))

In [ ]:
#Finding the max
aggregation_tensor.max(), torch.max(aggregation_tensor)

(tensor(90), tensor(90))

In [ ]:
#Finding the meam
torch.mean(aggregation_tensor)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
#We need to change the datatype as mean requires a tensor of datatype torch.float32
torch.mean(aggregation_tensor.type(torch.float32))

tensor(45.)

In [ ]:
#Finding the sum
torch.sum(aggregation_tensor)

tensor(450)

###Finding the positional min and max (Index Value)

In [ ]:
#Finding the positional min
torch.argmin(aggregation_tensor)

tensor(0)

In [ ]:
#Finding the positional max
torch.argmax(aggregation_tensor)

tensor(9)

##Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of a certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from the tensor
* UnSqueeze - adds a `1` dimension to the target tensor
* Permute - Return a view of the tensor with the dimensions permuted (swapped) in a certain way

In [ ]:
import torch
x = torch.arange(1., 10.)
x, x.shape, x.ndim

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), 1)

In [ ]:
#Adding an extra dimension
x_reshaped = x.reshape(1, 9)
print(x_reshaped, x_reshaped.shape)
x_reshaped2 = x.reshape(9, 1) #The two numbers should multiply to become the size of the original tensor e.g 1x9 = 9, 9x1 = 9, 3x3 = 9
x_reshaped2, x_reshaped2.shape

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])


(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
#Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#Changing z will change x (because view of a tensor shares the same memory as the original)
z[0,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
#Stack tensors on top of each other
x_vstacked = torch.stack([x, x, x, x], dim = 0) #vertical stack dimensionality = 0 (row wise)
print(x_vstacked)
x_vstacked2 = torch.vstack([x, x, x, x])
print(f"\n{x_vstacked2}")

x_hstacked = torch.stack([x, x, x, x], dim = 1) #horizontal stack dimenstionality = 1 (column wise)
print(f"\n{x_hstacked}")
x_hstacked2 = torch.hstack([x, x, x, x])
#hstack: Stack tensors in sequence horizontally (column wise).
#This is equivalent to concatenation along the first axis for 1-D tensors, and along the second axis for all other tensors.
print(f"\n{x_hstacked2}")

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9., 1., 2., 3., 4., 5., 6., 7., 8., 9.,
        1., 2., 3., 4., 5., 6., 7., 8., 9., 1., 2., 3., 4., 5., 6., 7., 8., 9.])


In [ ]:
#Squeezing a tensor, removes all 1 dimensions
print(f"Original Tensor {x_reshaped}")
print(f"Original Tensor shape {x_reshaped.shape}")
x_squeezed = x_reshaped.squeeze()
print(f"After squeezing tensor {x_reshaped.squeeze()}")
print(f"Shape of squeezed tensor {x_reshaped.squeeze().shape}")

Original Tensor tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Original Tensor shape torch.Size([1, 9])
After squeezing tensor tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Shape of squeezed tensor torch.Size([9])


In [ ]:
#torch.unqueeze() - adds a single dimension to a target tensor at a specific dimension
print(f"Squeezed Tensor: {x_squeezed}")
print(f"Squeezed Tensor shape: {x_squeezed.shape}")

#Adding an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim = 0) #dim specifies where to add the new dimension
print(f"The new unqueezed tensor: {x_unsqueezed}")
print(f"The new shape is: {x_unsqueezed.shape}")

Squeezed Tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Squeezed Tensor shape: torch.Size([9])
The new unqueezed tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
The new shape is: torch.Size([1, 9])


In [ ]:
#torch.permute() - rearranges the dimensions of a target tensor in a specified way (Shares memory like view)
x = torch.randn(2, 3, 5)
print(f"Previous shape : {x.size()}")
print(f"New shape : {torch.permute(x, (2, 0, 1)).size()}")
#(2, 0, 1)
#2: moves the number of elements in the 2nd dimension to the 0 th dimension
#0: moves the number of elements in the 0 th dimension to the 1 st dimension
#1: moves the number of elements in the 1 st dimension to the 2 nd dimension

Previous shape : torch.Size([2, 3, 5])
New shape : torch.Size([5, 2, 3])


In [ ]:
x_original = torch.rand(size = (224, 224, 3)) # [height, width, colour channels]

#Permuting the original tensor to rearrange the dimensions
x_permuted = torch.permute(x_original, (2, 0, 1)) # [colour channels, height, width]
# 2 --> 0, 0-->1, 1-->2
print(x_permuted.shape)

torch.Size([3, 224, 224])


In [ ]:
print(x_original[0,0,0])
x_original[0, 0, 0] = 5
print(x_original[0, 0, 0])
print(x_permuted[0, 0, 0])

tensor(0.8657)
tensor(5.)
tensor(5.)


## Selecting data from tensors (Indexing)
Indexing with pytorch is similar to indexing with numpy

In [ ]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
#Indexing on x
x[0] #Indexed on the 0 th dimension

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0] #Indexed on the middle bracket (1 st Dimension)

tensor([1, 2, 3])

In [ ]:
x[0][0][0] #Indexed on the inner most bracket (Last Dimesion , 2nd)


tensor(1)

In [ ]:
#You can also use ":" to get "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
#Get all values of 0 th and 1 st dimension but only index one of 2 nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
#Get all values of the 0 th dimension but only the 1 index value of 1 st and 2 nd dimension
x[:,1,1]

tensor([5])

In [ ]:
#Get index 0 of 0th and 1 st dimension and all values of 2 nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
print(x)
#Index on x to return 9
print(x[0][2][2])
#Index on x to return 3, 6, 9
x[:, :, 2]
#All of the elemenrs in the 0 th dimension(whole outermost bracket included)
#All of the elements in the 1 st dimension(whole middle bracket included so all rows included)
#[2] Only the second index from all of the included rows

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor(9)


tensor([[3, 6, 9]])

## Pytorch and Numpy
* Data may be in numpy array and we want in pytorch tensor -> `torch.from_numpy(ndarray)`
*Pytorch tensor to numpy -> `torch.Tensor.numpy()`

In [ ]:
#numpy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 10.0)
tensor = torch.from_numpy(array)#.type(torch.float32)
array, tensor
# NOTE :- Default datatype in pytorch is float32 whereas default numpy datatype is float64
#When converting pytorch reflects numpys default type of float64

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [ ]:
tensor = tensor.type(torch.float32)
print(tensor.dtype)
#Converting the datatype

torch.float32


In [ ]:
#Will changing the array change the tensor?
array = array + 1
array, tensor
#NO

(array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
#From tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor
#THE DEFAULT DATATYPE IS REFLECTED

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
#Will changing the tensor change the numpy tensor?
tensor = tensor + 1
tensor, numpy_tensor
#NO

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

##Reproducibility:- The process of taking the random out of random
How neural networks learn:-
`start with random numbers -> tensor operations -> update random numbers to try and make them better representation of the data`

To reduce the randomness in neural networks and pytorch comes the concept of **random seed**
random seed flavours the randomness


In [ ]:
import torch

random_tensorA = torch.rand(3, 4)
random_tensorB = torch.rand(3, 4)
print(random_tensorA)
print(random_tensorB)
print(random_tensorA == random_tensorB)

tensor([[0.2148, 0.8337, 0.7952, 0.7825],
        [0.5507, 0.9798, 0.9877, 0.8597],
        [0.4397, 0.1534, 0.4472, 0.2686]])
tensor([[0.6912, 0.4391, 0.9395, 0.1178],
        [0.9215, 0.5339, 0.1181, 0.5125],
        [0.6713, 0.8311, 0.5185, 0.1304]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
#Random but reproducible tensors
#Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensorC = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED) # ONLY WORKS FOR ONE LINE OF CODE
random_tensorD = torch.rand(3, 4)
print(random_tensorC)
print(random_tensorD)
print(random_tensorC == random_tensorD)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


###Running tensors on GPUs and making faster computations

In [ ]:
#Check for gpu access on pytorch
import torch
torch.cuda.is_available()


True

In [ ]:
#Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
#Creating a tensor, default on cpu
tensor = torch.tensor([1, 2, 2])
print(tensor, tensor.device)

tensor([1, 2, 2]) cpu


In [ ]:
#Moving tensor to GPU
tensor_GPU = tensor.to(device) # or "cuda" instead of device
tensor_GPU

tensor([1, 2, 2], device='cuda:0')

In [ ]:
#Moving tensors back to cpu
#NUMPY DOES NOT WORK ON GPU SO NEED TO SHIFT TO CPU
tensor_CPU = tensor_GPU.to("cpu") #or use tensor_GPU.cpu()
tensor_CPU, tensor_CPU.device

(tensor([1, 2, 2]), device(type='cpu'))

##EXERCISES
https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises

In [ ]:
import torch

In [ ]:
#1.
tensor1 = torch.rand(7, 7)
print(tensor1, tensor1.shape)

tensor([[0.8688, 0.0966, 0.9084, 0.2896, 0.7504, 0.0758, 0.2901],
        [0.6105, 0.2902, 0.9673, 0.4704, 0.0028, 0.6970, 0.1629],
        [0.3006, 0.2346, 0.8110, 0.5967, 0.2009, 0.9799, 0.4493],
        [0.8846, 0.1133, 0.4878, 0.0941, 0.8848, 0.8436, 0.4307],
        [0.3823, 0.9969, 0.5473, 0.3033, 0.1692, 0.7224, 0.6249],
        [0.8729, 0.4253, 0.0417, 0.8982, 0.6889, 0.1306, 0.1386],
        [0.2737, 0.6718, 0.3093, 0.9013, 0.1046, 0.7212, 0.3952]]) torch.Size([7, 7])


In [ ]:
tensor2 = torch.rand(1, 7)
print(f"Original tensor number 2 is {tensor2} and shape is {tensor2.shape}")
print(f"\nThe transposed tensor 2 is \n {tensor2.T}")
print(f"\n The new shape is {tensor2.T.shape}")

tensor3 = torch.matmul(tensor1, tensor2.T) # (7, 7) * (1, 7) : Inner dimensions dont match so transpose
print(f"\n The result of tensor multiplication is \n {tensor3}")


Original tensor number 2 is tensor([[0.3362, 0.9440, 0.8510, 0.3015, 0.4360, 0.4281, 0.3216]]) and shape is torch.Size([1, 7])

The transposed tensor 2 is 
 tensor([[0.3362],
        [0.9440],
        [0.8510],
        [0.3015],
        [0.4360],
        [0.4281],
        [0.3216]])

 The new shape is torch.Size([7, 1])

 The result of tensor multiplication is 
 tensor([[1.6966],
        [1.7962],
        [1.8442],
        [1.7332],
        [2.2107],
        [1.4021],
        [1.7426]])


In [ ]:
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
tensor1 = torch.rand(7, 7)
print(f"Original tensor number 1 is \n {tensor1} and shape is {tensor1.shape}")

#torch.manual_seed(RANDOM_SEED)
tensor2 = torch.rand(1, 7)

print(f"\nOriginal tensor number 2 is {tensor2} and shape is {tensor2.shape}")
print(f"\nThe transposed tensor 2 is \n {tensor2.T}")
print(f"\n The new shape is {tensor2.T.shape}")

tensor3 = torch.matmul(tensor1, tensor2.T) # (7, 7) * (1, 7) : Inner dimensions dont match so transpose
print(f"\n The result of tensor multiplication is \n {tensor3}")

Original tensor number 1 is 
 tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]) and shape is torch.Size([7, 7])

Original tensor number 2 is tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]]) and shape is torch.Size([1, 7])

The transposed tensor 2 is 
 tensor([[0.4820],
        [0.8198],
        [0.9971],
        [0.6984],
        [0.5675],
        [0.8352],
        [0.2056]])

 The new shape is torch.Size([7, 1])

 The result of tensor multiplication is 
 tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
 

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)

In [ ]:
torch.manual_seed(1234)
tensor1 = torch.rand(size = (2, 3), device = "cuda")
torch.manual_seed(1234)
tensor2 = torch.rand(size = (2, 3), device = "cuda")
print(f"The first tensor is \n {tensor1}")
print(f"The second tensor is \n {tensor2}")


The first tensor is 
 tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')
The second tensor is 
 tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')


In [ ]:
tensor2 = tensor2.T
tensor3 = torch.matmul(tensor1, tensor2)
print(f"The result of multiplication of the two tensors is \n {tensor3}")

The result of multiplication of the two tensors is 
 tensor([[0.9792, 0.8358],
        [0.8358, 1.4578]], device='cuda:0')


In [ ]:
max = torch.max(tensor3)
print(f"The max value in the result is {max}")
min = torch.min(tensor3)
print(f"The min value in the result is {min}")

maxIndex = torch.argmax(tensor3)
print(f"The max value index in the result is {maxIndex}")
minIndex = torch.argmin(tensor3)
print(f"The min value index in the result is {minIndex}")

The max value in the result is 1.4577524662017822
The min value in the result is 0.8358409404754639
The max value index in the result is 3
The min value index in the result is 1


In [ ]:
torch.manual_seed(7)
tensor1 = torch.rand(size = (1, 1, 1, 10))
print(f"The original tensor 1 is \n {tensor1} and the shape is \n {tensor1.shape}")
tensor2 = torch.squeeze(tensor1)
print(f"The original tensor after being squeezed to remove 1 dimensions is \n {tensor2} and the shape is {tensor2.shape}")


The original tensor 1 is 
 tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) and the shape is 
 torch.Size([1, 1, 1, 10])
The original tensor after being squeezed to remove 1 dimensions is 
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) and the shape is torch.Size([10])


##Exercise complete and Pytorch Fundamentals Completed